### ISSUE TITLE
Enable easy navigation between oai-pmh resources

### ISSUE THREAD

**Issue by abollini** [openaire/guidelines-cris-managers#5]
In the current example there is not automatic way to figure out which is the oai:identifier of a referenced resource, see
https://github.com/openaire/guidelines-cris-managers/blob/master/samples/openaire_cerif_xml_example_publications.xml#L34
> <Person id="2123455">

it will be convenient to force the implementer to provide a standard way to retrieve the person record over oai-pmh, it could be done in two ways

1) we can mandate to use the following oai:identifier structure <your-oai-identifier-base>:<entityType>:<internalId> i.e. oai:cris.example.org:cfPerson/2123455
or
2) we can recommend to include a FederatedIdentifier in the linked resource (the person sub-record in our example) to specify the oai identifier for such record if exposed over the same oai-pmh server

Personally I prefer the solution 2 as it impose less to the implementers. It also makes possible to have some persons not exposed at all over oai-pmh if not relevant for the CRIS system (i.e. co-authors from external organisations) in a way predicable by the OAI-PMH clients (no identifier --> no further information available)

**Comment by jdvorak001** [comment]
Andrea, you write about two options. I do not see them as one excluding the other. I agree we should convert to full OAI:identifiers, so that the navigation is consistent. (Even though the need for it will be greatly reduced because of the partial de-normalization we are introducing.)
I will commit the 

The choice then is between
1. putting this identifier in the "id" attributes (the internal identifiers) 
and 
2. using a CERIF federated identifier for this identifier.

Please note that the "id" attributes are not mandatory in CERIF XML.

**Comment by jdvorak001** [comment]
My preference would be to use the "id" attributes, as it's identifiers **in the source CRIS**.

**Comment by jdvorak001** [comment]
Summary of discussion:
* id attribute contains the 'raw' value of the identifier;
* federated identifiers contain possible other representations of the identifier, such as a CERIF REST API URI

**Comment by jdvorak001** [comment]
The documentation (somewhere in http://openaire-guidelines-for-cris-managers.readthedocs.io/en/latest/implementation.html#oai-identifiers) should contain a statement that persistent internal identifiers should be preferred. UUIDs should be preferred to integers.
